export const GET_ALL_URLS='GET_ALL_URLS';
export const GET_ALL_URLS_SUCCESS='GET_ALL_URLS_SUCCESS';
export const GET_ALL_URLS_FAILURE='GET_ALL_URLS_FAILURE';
export const POST_NEW_URL_SUCCESS='POST_NEW_URL_SUCCESS';
export const POST_NEW_URL_FAILURE='POST_NEW_URL_FAILURE';
export const POST_NEW_URL='POST_NEW_URL';
export const START_LOADING='START_LOADING';
export const INCREASE_CLICK_COUNT="INCREASE_CLICK_COUNT";